### ISSUE TITLE
Problem to include up other svelte libraries

### ISSUE THREAD

**Issue by rsbroetto** [wewowweb/laravel-mix-svelte#2]
I'm trying to use a  package called svelte-routing within a laravel app that i'm work on it. I already have a svelte+laravel integration working just fine. But i'm having some troubles when i attempt to include any module from svelte-routing. for example, into my App.svelte, this line causes to break my compilation:

```
import { Router, Link, Route } from "svelte-routing";
```

For sure is a problem with the loaders. I know **laravel-mix-svelte** compile down all *.svelte files within resources directory, but i think  when i try to include files from node_modules directory it causes some trouble.  

As a workaround, i remove line 12 from "laravel-mix-svelte/src/index.js" 
```
exclude: /node_modules/
```
and then, everything works fine, like a charm. I dont know if there is some side effects from removing this line, or if i can pass to svelte-mix extension the options that i want to.

thanks.

**Comment by morpheus7CS** [comment]
Hey @rsbroetto,

do you have a repository with that code available? Just so that I can see it and try to help.

Thanks,
g

**Comment by morpheus7CS** [comment]
Hey there again @rsbroetto,

I have been digging some more and realized that you have correctly identified the issue. The solution has been implemented as described by you about 9 hours back in [webpack.config.js](https://github.com/sveltejs/template-webpack/blob/master/webpack.config.js) file inside Svelte's webpack-template repository.

The issue should be fixed in the [v.0.1.2](https://github.com/wewowweb/laravel-mix-svelte/releases/tag/v.0.1.2) release.

Thanks for reporting the bug!
g
