### ISSUE TITLE
Update npm with v0.1.4 release?

### ISSUE THREAD

**Issue by jawish** [wewowweb/laravel-mix-svelte#8]
The v0.1.4 tag does not seem to have a release on NPM yet. It has pretty important fixes by way of the changes merged in https://github.com/wewowweb/laravel-mix-svelte/pull/6 that allows working with Svelte component libraries.

Any chance you could push the release to NPM? Thanks!

**Comment by morpheus7CS** [comment]
Hey @jawish,

thanks for reporting it. I've had the same issue a couple of times, which is due to me forgetting to update the versioning. I just fixed it and corrected the error with the [v0.1.5](https://github.com/wewowweb/laravel-mix-svelte/releases/tag/v0.1.5) release, which is also available on NPM.

I'll also look into automating this part of the process through Github, so that it doesn't happen again.  
  
Kind regards,

g

**Comment by jawish** [comment]
@morpheus7CS Thanks for the swift action!
